version: '3.8'

services:
  flask-app:
    build:
      context: .  # Path flask app.py
      dockerfile: Dockerfile
    ports:
      - "5000:5000"


  laravel-app:
    build:
      context: ./hr-web  # Path LARAVEL
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./hr-web:/var/www



volumes:
  db_data:
