version: '3.8'

services:
  flask-app:
    build:
      context: .  # Path flask app.py
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - db-data:/var/www/storage/app/public
    environment:
      - LARAVEL_STORAGE_BASE=var/www/storage/app/public

  laravel-app:
    build:
      context: ./hr-web  # Path LARAVEL
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./hr-web:/var/www
      - db-data:/var/www/storage/app/public

volumes:
  db-data:
